In [58]:
import requests
import json
from scrapy.http import HtmlResponse

url = f"https://info.securities-administrators.ca/disciplinedpersons.aspx"

payload = "__EVENTTARGET: ctl00$bodyContent$lbtnNext2"
headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
}

res = requests.post(url, headers=headers, data=payload)

In [1]:
from deep_translator import GoogleTranslator
def langtranslation(to_translate):
    try:
        translated = GoogleTranslator(source='auto', target='en').translate(to_translate)
    except:
        try:
            translated = GoogleTranslator(source='auto', target='en').translate(to_translate)
        except:
            print(f">>>Translartion Bug : {to_translate}")
            translated = to_translate   
    return translated

# -*- coding: utf-8 -*-
def isEnglish(s):
    try:
        s.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True

In [46]:
import camelot

In [3]:
tb = camelot.read_pdf("raw-files/file-157415407029476.pdf",pages="1",flavor="stream")
# tb = camelot.read_pdf("raw-files/file-157415407029476.pdf",pages="1",flavor="stream")

In [47]:
main = tb[0].df
new_header = main.iloc[0] #grab the first row for the header
main = main[1:] #take the data less the header row
main.columns = new_header #set the header row as the df header
main

,Arabic Name\n يبرعلاب مسلاا,English Name\n يزيلجنلااب مسلاا,Code\nزمرلا,,Arabic Address\n يبرعلاب ناونعلا,English Address\nيزيلجنلااب ناونعلا
1,يملاسلاا دلابلا,Al Bilad Islamic,BIQ034/2,,ةيرحلا ةحاس برق\n /\n ةداركلا\n /\n دادغب,Baghdad / Karrada / near Al Horriya square
2,يملاسلاا يميلقلاا نواعتلا,Islamic Regional Co-operation,BIQ036/2,,59\n ةيانب\n / \n17\n عراش\n / \n929\n ةلحم\n ...,Baghdad / Al Masbah / section 929 / street 17 ...
3,ناريا يلم,Melli Iran,BIQ037/2,,27\n قاقز\n / \n929\n ةلحم\n /\n تاصرعلا\n /\n...,Baghdad / Al Arasat / sectiom 929 / lane 27
4,نايسراب,Barsian,BIQ052/2,يملاسلاا ينطولا فرصملا لباقم\n /,69\n ةيانب\n /\n30\n عراش\n / \n929\n ةلحم\n /...,Baghdad / Karrada / Babil neighborhood / Al Ar...
5,تارفلاو هلجد,Dijlah wa Al Furat,EIQ0255/3,,19\n قاقز\n / \n110\n ةلحم\n /\n ديشرلا عراش\n...,Baghdad / Al Rasheed street / section 110 / la...
...,...,...,...,...,...,...
104,,Afaq Dubai,,,,Nishtiman Exchange Market
105,,Reydin,,,,Sheikhallah Exchange Market
106,,Al Khalidi Exchange,,,,Irbil / New Borsa / Nishtaman Building second ...
107,ءاطعلا,Al Attaa,BIQ034/2,,ةيرحلا ةحاس برق\n /\n ةداركلا\n /\n دادغب,Baghdad / Karrada / near Al Horriya square
108,ليومتلاو رامثتسلال يملاسلاا قارعلا رون فرصم,Noor Al Iraq,BIQ064/2,,ةنامرهك ةحاس برق\n /\n ةداركلا\n /\n دادغب,Baghdad / Karrada / near Kahramana sequer

In [48]:
import hashlib
from datetime import datetime
last_updated_string = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
def get_hash(n):
    return hashlib.sha256(((n+"Central Bank of Iraq Public Black List, Iraq" + "IRQ_T30064").lower()).encode()).hexdigest()

In [53]:
out_list1 = []
for i,row in main.astype(str).iterrows():
    pass_dict = {}
    name = row["English Name\n يزيلجنلااب مسلاا"]
    code = row["Code\nزمرلا"]
    pass_dict["uid"] = get_hash(code+name)
    pass_dict["name"] = name

    pass_dict["alias_name"] = [row["Arabic Name\n يبرعلاب مسلاا"]]

    pass_dict["list_type"] = "Entity"
    pass_dict["nns_status"] = "False"
    pass_dict["last_updated"] = last_updated_string
    pass_dict["list_id"] = "IRQ_T30064"
    pass_dict["country"] = ["Iraq"]

    comp = row["English Address\nيزيلجنلااب ناونعلا"]
    comp = comp.split(" / ")
    comp.reverse()
    comp = ",".join(comp)
    pass_dict["address"] = []
    pass_dict["address"].append({
        "complete_address": comp,
        "country" : "Iraq"
    })
    pass_dict["sanction_details"] = {}
    pass_dict["entity_details"] = {}
    pass_dict["comment"] = ""
    pass_dict["sanction_list"] = {}
    pass_dict["sanction_list"] = {
            "sl_authority": "Central Bank of Iraq, Iraq",
            "sl_url": "https://cbi.iq/news/view/741",
            "watch_list": "EMEA Watchlists",
            "sl_host_country": "Iraq",
            "sl_type": "Sanctions",
            "sl_source": "Central Bank of Iraq Public Black List, Iraq",
            "sl_description": "List of individuals and entities sanctioned by Central Bank of Iraq, Iraq"
        }

    out_list1.append(pass_dict)

In [50]:
out_list1[-1]
len(out_list1)

108

In [15]:
import pandas as pd
main = pd.read_excel("raw-files/Book 1.xlsx")

In [25]:
in_main = main[0:94]
en_main = main[95:]
en_main

,أسماء شركات التوسط,Name,Code,Arabic,English,Day,Month,Year
95,سلسلة الذهب,Selselat Al Thahab,TIQ026/1,كربﻻء,Karbala,15.0,5.0,2016.0
96,النبال العربية,Al Nibal Al Arabia,TIQ001/1,بغداد,Baghdad,8.0,1.0,2016.0
97,النهر الخالد,Al Nahr Al Khalid,TIQ004/1,بغداد,Baghdad,6.0,6.0,2017.0
98,الوائل,Al Wa'eel,TIQ019/1,بغداد,Baghdad,15.0,5.0,2016.0
99,مصرف العطاء اﻻسﻻمي (البﻻد سابقا),Al Ataa Islamic Bank,BIQ034/2,بغداد,Baghdad,16.0,5.0,2018.0
100,مصرف التعاون اﻷسﻻمي لﻷستثمار,Islamic Cooperation Bank for Investment,BIQ036/2,بغداد,Baghdad,8.0,1.0,2016.0
101,بنك ملي ايران,Bank Melli Iran,BIQ037/2,بغداد,Baghdad,8.0,1.0,2016.0
102,مصرف نور العراق اﻻسﻻمي لﻻستثمار \nوالتمويل,Iraq Noor Islamic Bank \nfor Investment & Fin...,BIQ064/2,بغداد,Baghdad,30.0,10.0,2019.0
103,بنك بارسيان,Parsian Bank,BIQ052/2,بغداد,Baghdad,8.0,1.0,2016.0
104,مصرف بابل,Babylon Bank,BIQ019/2,بغداد,Baghdad,24.0,12.0,2020.0

In [28]:
main.columns

Index(['أسماء شركات التوسط ', 'Name', 'Code', 'Arabic ', 'English', 'Day',
       'Month', 'Year'],
      dtype='object')

In [44]:
def tab_scrap(m,t):
    pass_list = []
    for i,r in m.astype(str).iterrows():
        name = r["Name"]
        code = r["Code"]
        uid = get_hash(name+code)

        alias = [r["أسماء شركات التوسط "]]

        comp = r["English"]
        adrs = [{
            "complete_address" : f"{comp.strip()},Iraq",
            "country" : "Iraq"
        }]

        date  = f"{r['Day']}/{r['Month']}/{r['Year']}"
        
        if t == "e":
            pass_list.append(
            {
                "uid":uid,
                "name":name,
                "alias_name": alias,
                "country": ["Iraq"],
                "list_type": "Entity",
                "last_updated": last_updated_string,
                "list_id": "IRQ_T30064",
                "entity_details": {},
                "nns_status": "False",
                "address": adrs,
                "sanction_details": {
                    "date" : date 
                                    },
                "comment":"",
                "sanction_list": {
                    "sl_authority": "Central Bank of Iraq, Iraq",
                    "sl_url": "https://cbi.iq/news/view/741",
                    "watch_list": "EMEA Watchlists",
                    "sl_host_country": "Iraq",
                    "sl_type": "Sanctions",
                    "sl_source": "Central Bank of Iraq Public Black List, Iraq",
                    "sl_description": "List of individuals and entities sanctioned by Central Bank of Iraq, Iraq"
                }
            }
            )
        else:   
            pass_list.append(
            {
                "uid":uid,
                "name":name,
                "alias_name": alias,
                "country": ["Iraq"],
                "list_type": "Individual",
                "last_updated": last_updated_string,
                "list_id": "IRQ_T30064",
                "individual_details": {},
                "nns_status": "False",
                "address": adrs,
                "sanction_details": {
                    "date" : date 
                                    },
                "comment":"",
                "sanction_list": {
                    "sl_authority": "Central Bank of Iraq, Iraq",
                    "sl_url": "https://cbi.iq/news/view/741",
                    "watch_list": "EMEA Watchlists",
                    "sl_host_country": "Iraq",
                    "sl_type": "Sanctions",
                    "sl_source": "Central Bank of Iraq Public Black List, Iraq",
                    "sl_description": "List of individuals and entities sanctioned by Central Bank of Iraq, Iraq"
                }
            }
            )
    return pass_list

In [45]:
out1 = tab_scrap(en_main,"e")
out2 = tab_scrap(in_main,"i")
print(len(out1))
print(len(out2))

10
94

In [54]:
main_out = out_list1 + out1 + out2
len(main_out)

212

In [58]:
import json
with open("sng-711.json", "w",encoding='utf-8') as outfile:
    json.dump(main_out, outfile, ensure_ascii=False, indent=4)